### ISSUE TITLE
How to deal with drs4 baseline and spike correction in case of EVB pre-calibrated data

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe_io_lst#200]
EVBv6 will be able to stored calibrated waveforms in pe units, but spike correction is not yet implemented.

So we'll probably a) need to live with higher noise or b) scale spike heights by the applied gain.
Which leaves the question how to know which gain was applied by EVB.

**Comment by FrancaCassol** [comment]
Hi @maxnoe, Julien Houle  is well aware that the EVB must implement the spike subtraction, however the method is not updated inside the DRS4 correction document https://edms.cern.ch/ui/file/2397593/0.3/DRS4_correction_procedures_v0.3c.pdf . He asked to update it in order to have guide for the implementation. @pawel21 or @jsitarek would be it possible to have the original version of the document in order to perform the update?

**Comment by maxnoe** [comment]
@FrancaCassol Let's discuss the details of spike correction in EVB in the lst daq issue tracker: https://redmine.cta-observatory.org/projects/idaq/issues where Julien and Dirk are active.

This is about dealing with the data  offline  before that implementation is done.

**Comment by maxnoe** [comment]
Note: same issue applies for the "relative" drs4 correction, i.e. correcting the data that was corrected with some baseline coefficients with more current ones.

**Comment by maxnoe** [comment]
We made the decision that we won't try to improve upon the drs4 corrections applied by EVB here.
