### ISSUE TITLE
Change number of samples to 36 for dealing with new data format from EVB v6.5+

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/ctapipe_io_lst#227]
How do we deal with this? Choose the number of samples based on the EVB version used?

In principle, by changing it here it works (at least the drs4 baseline file production):

https://github.com/cta-observatory/ctapipe_io_lst/blob/a145edd8a5470335ca3be6244d68c277f80caf33/src/ctapipe_io_lst/constants.py#L13

Some more changes need to be done downstream in lstchain. For example, for calibration checks it needs to be also changed `drs4.plot_pedestals`

```python
...
ValueError: x and y must have same first dimension, but have shapes (36,) and (33,)
```

**Comment by maxnoe** [comment]
The number of samples is in the data actually.

But the issue is more complex than that. It is only easy to support EVB removing samples if we don't need to perform offline DRS4 corrections. 

Removing samples changes the relationship between the position in the waveform and the `first_cell_id`, it would require extensive changes of the DRS4 correction code.
I am opposed to implementing this for this intermediate state.

Removal of samples should only be switched on in EVB if and only if all other DRS4 corrections are also applied.
