### ISSUE TITLE
Flatfield tagging misses some flatfield events

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/ctapipe_io_lst#97]
This can be seen in page 6 of https://www.lst1.iac.es/datacheck/dl1/v0.7.1/20201117/datacheck_dl1_LST-1.Run02912.pdf: there is a peak in the charge & intensity spectra of cosmics, which corresponds to flatfield events

This was not the case with lstchain's older (0.6.3) tagging:
https://www.lst1.iac.es/datacheck/dl1/v0.6.3_v05/20201117/datacheck_dl1_LST-1.Run02912.pdf

**Comment by FrancaCassol** [comment]
Hi @moralejo, 
this due to a different tagging strategy adopted in the new source. I hope it is solved with PR [681](https://github.com/cta-observatory/cta-lstchain/pull/681#pullrequestreview-631448310)

By the way, since some weeks, also the calibox trigger is active, so we should add the possibility to use also that tagging (preliminary studies show that is marginally less efficient than the standard one) for the FF selection with filter 52. But this will be useful overall for the low intensity runs in the filter scans. I will propose a PR in ctapipe_io_lst (this  does not concerns the coming production)

**Comment by moralejo** [comment]
Hi, yes, I think #681 fixes the issue (which showed up only on one of the reprocessed nights). As for using the event tagging from TIB, I see no urgency. Until the system is 100% reliable I would not switch to using it for the FF tagging.
